services:
  - type: web
    name: enterprise-crm-backend
    env: node
    region: oregon
    plan: free
    rootDir: backend
    buildCommand: cd ../frontend && npm install && npm run build && cd ../backend && npm install
    startCommand: node server.js
    envVars:
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: CLIENT_URL
        value: https://enterprise-crm-backend-bfqm.onrender.com
